name: Update File

on:
  schedule:
    - cron: "*/5 * * * *" # Runs every 5 minutes (adjust as needed)

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Generate Random Key
        run: |
          echo "encrypt-$(openssl rand -hex 2)-$(openssl rand -hex 2)-$(openssl rand -hex 2)" > key.txt

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add file.txt
          git commit -m "Automated update with new key" || exit 0
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
